---
name: "Darker"
description: "Apply Black, isort and linters to modified lines only."
author: "Antti Kaihola and contributors to Darker"
inputs:
  options:
    description: >-
      Options passed to Darker. Use `darker --help` to see available options.
      Default: '--check --diff --color'
    required: false
    default: "--check --diff --color"
  src:
    description: "Source to run Darker. Default: '.'"
    required: false
    default: "."
  version:
    description: 'Version of Darker to use, e.g. "~=2.1.0", "2.1.0", "@master"'
    required: false
    default: "~=2.1.0"
  revision:
    description: >-
      Git revision range to compare when determining modified lines.
      Determined automatically if omitted.
    required: false
  lint:
    description: >-
      Comma-separated list of linters to `pip install` and run from Darker.
      Optionally, version constraints (using pip syntax) can be specified.
      Example: flake8,pylint==2.13.1
    required: false
    default: ''
branding:
  color: "black"
  icon: "check-circle"
runs:
  using: composite
  steps:
    - name: Commit Range
      id: commit-range
      uses: akaihola/darker/.github/actions/commit-range@1.7.1
    - name: Run Darker
      run: |
        # Exists since using github.action_path + path to main script doesn't
        # work because bash interprets the backslashes in github.action_path
        # (which are used when the runner OS is Windows) destroying the path to
        # the target file.
        #
        # Also semicolons are necessary because I can't get the newlines to work
        entrypoint="import sys;
        import subprocess;
        from pathlib import Path;

        MAIN_SCRIPT = Path(r'${{ github.action_path }}') / 'action' / 'main.py';

        proc = subprocess.run([sys.executable, str(MAIN_SCRIPT)]);
        sys.exit(proc.returncode)
        "

        pip install pip-requirements-parser
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo $entrypoint | python
        else
          echo $entrypoint | python3
        fi
      env:
        # TODO: Remove once https://github.com/actions/runner/issues/665 is
        #       fixed.
        INPUT_OPTIONS: ${{ inputs.options }}
        INPUT_SRC: ${{ inputs.src }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_REVISION: ${{ inputs.revision }}
        INPUT_LINT: ${{ inputs.lint }}
        INPUT_COMMIT_RANGE: ${{ steps.commit-range.outputs.commit-range }}
        pythonioencoding: utf-8
      shell: bash
