---
name: Test linting using the Darker GitHub Action

on: push  # yamllint disable-line rule:truthy

jobs:
  darker-github-action-linting-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Darker
        uses: akaihola/darker@1.7.0
        with:
          options: -vvv --check --diff --color --isort --config pyproject.toml
          revision: origin/master...
          lint: flake8
