---
name: Recent Activity Summary
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # Allow manual triggering

jobs:
  prs:
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Summary Action
        uses: akaihola/repo-summary-post
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ github.repository }}
          # category: 'General'  # Don't post discussion yet
