---
name: test-future

# This workflow detects breakage against upcoming releases of dependencies
# even in the absence of activity in Darker's own repository.

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "05 20 * * 6"
  workflow_dispatch:

jobs:
  test-future:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          cache-dependency-glob: |
            **/setup.cfg
            **/pyproject.toml
      - name: Install Darker and its dependencies
        run: uv pip install --group=dev .
      - name: Upgrade dependencies to future versions
        # Upgrade Black, Flynt and Isort from GitHub.
        # This can't be done in the same uv invocation as installing Darker
        # since Darker might place an upper limit on Black, Flynt and/or Isort during
        # compatibility fixing periods.
        run: uv pip install
               --upgrade
               --requirements constraints-future.txt
      - name: Test with pytest
        run: uv run pytest

      - name: Note a possible Black incompatibility and required actions
        if: failure()
        shell: python
        run: |
          import json
          import os
          import urllib.request
          from textwrap import dedent

          from packaging.version import Version

          for linenum, line in enumerate(open("pyproject.toml"), 1):
              if '"black>=' in line:
                  column = line.index("black>=")
                  end_column = line.rindex('"')
                  constraint = line[column:end_column]
                  break
          else:
              raise RuntimeError("black>= line not found in pyproject.toml")

          response = urllib.request.urlopen(
              'https://pypi.org/pypi/black/json'
          ).read().decode()
          latest_version = max(
              Version(s)
              for s in json.loads(response)['releases'].keys()
          )

          print(
              dedent(
                  f"""
                  ### :x: Future Black incompatibility? :x:

                  You could add a maximum version constraint for Black on
                  `setup.cfg` line {linenum}, e.g.
                  `{constraint},<={latest_version}`

                  See [#382](/akaihola/darker/issues/382)
                  for more information
                  """
              ),
              file=open(os.getenv("GITHUB_STEP_SUMMARY"), "a"),
          )

          print(
              "::notice "
              "file=setup.cfg,"
              f"line={linenum},"
              f"col={column + 1},"
              f"endColumn={end_column + 1},"
              "title=Future Black incompatibility?::"
              "You could add a maximum version constraint for Black here, "
              f"e.g. {constraint},<={latest_version}"
          )
